### ISSUE TITLE
Roadmap 1.0

### ISSUE THREAD

**Issue by hallelujah** [3scale/minitest-random_failures#2]
# TODO

- [ ] Improve README.md
- [x] Add motivation why this gem #6
- [ ] Add more tests
- [ ] Setup CI #3 
- [ ] Allow report to embed test files to require instead of passing them through `--test-files` #4
- [ ] Stabilize command name, option names
- [ ] Improve Dichotomy algorithm #5 
- [ ] Create the Combination algorithm
- [ ] Allow the use of different algorithm in sequences
- [ ] Code of conduct? yes or no?
- [ ] Improve the output of `./bin/minitest_random_failures` output
